### ISSUE TITLE
express 및 mariadb를 적용한 app서버 구축

### ISSUE THREAD

**Issue by DGChoi3904** [kongukjae/KDT-2-Project-A-4#15]
issue12에서 시도한 express mariadb 각개 모듈화 작업을 진행결과, 전부 모듈화 하여 사용하기엔 DB서버와의 통신로직을 짜기가 어려울 것으로 보임(좀 더 학습이 필요)
그렇기에 mariadb만 모듈화하고 한페이지에서 작업하여 클라이언트 ↔ 서버 ↔ DB서버 통신을 구현하고자 합니다.
새로 이슈를 판 이유는 express를 설치하고 package를 병합하려 하니 병합충돌이 일어났기에 이를 해결하기 위해서 새로 파서 진행했습니다.

**Comment by EXPNUNI-HUB** [comment]
express를 설치하고 package를 병합하려 하니 병합충돌이 일어났기
 이에 대한 오류 메세지 공유 부탁.

**Comment by DGChoi3904** [comment]
확인했습니다. 다음부턴 메세지 해석 및 이유를 명확히 하겠습니다.
감사합니다.
