### ISSUE TITLE
개발 환경 재구축

### ISSUE THREAD

**Issue by DGChoi3904** [kongukjae/KDT-2-Project-A-4#20]
프로젝트를 위한 개발 환경 단계별 재구축을 진행.
이는 추후 환경 구축 절차를 확인 가능하도록 구축 하고 문제 발생시 어느 단계에서 발생했는지 추적하기 쉽게하기 위함.

**Comment by DGChoi3904** [comment]
에러 내용 
이슈#2
커밋 번호 : bdda3730cc1dab211b66a1b3a99a2ebe10a63cbc

해당 커밋의 파일을 ts-node로 실행시 다음과 같은 에러가 발생.
S C:\VS Code\KDT-2-Project-A-4> npx ts-node ./develop/index.ts
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for C:\VS Code\KDT-2-Project-A-4\develop\index.ts
    at new NodeError (node:internal/errors:399:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:79:11)   
    at defaultGetFormat (node:internal/modules/esm/get_format:121:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:605:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}

npx tsc로 컴파일은 문제 없이 진행되나, ts-node로 바로 실행할 때에만 해당 에러 발생. 
에러 원인은 package에 type:module을 적용하여 생긴 문제라고 하며, ts-node의 기본 옵션이 commonJS방식이기 때문에 그렇다는 것을 확인함.
이 경우 ts-node 를 사용할 때 다음과 같이 명령어를 작성하여 사용할 것을 확인.

ts-node --esm index.ts

ts-node에서 --esm 옵션을 넣어 ESM 방식으로 읽는다고 명시해야 실행된다고 함.

결론 : 문제의 원인은 webpack.config.js 및 다른 JS로 작성할 모듈을 ESM모듈 방식으로 작성하려 하여 패키지에 type:module을 적용한 것. 추후 이것이 문제될 가능성이 있다면 수정해야 할 것으로 보인다.

**Comment by DGChoi3904** [comment]
TS에서 React 타입명 정의.
레퍼런스 : 
https://www.typescriptlang.org/ko/docs/handbook/jsx.html

TS환경으로 JSX Component를 만들경우, 타입지정시 null | undefined 타입 지정 관련 에러가 뜬다. 이를 해결해보기위해 root.render()시 뜨는 children 매개변수의 티압인 React.ReactNode를 적용해보았으나 해결되지 않았다.

검색해보니 JSX를 사용시 각 컴포넌트는 작성 방식에 따라 타입명을 다르게 지정해주어야 한다고 명시되어 있다.
타입은 다음과 같았다.
함수형 컴포넌트 - JSX.Elements 
클래스형 컴포넌트 - JSX.ElementClass

이를 통해 TS로 작업시 작성 방식에 따라 주어야 함을 확인했고, 다음과 같이 적용하니 에러메세지가 사라진 것을 확인 가능햇다.

```
import * as React from "react";
import {createRoot} from "react-dom/client";

// TS에서는 React.ReactNode를 배정하면 이해하지 못한다. 그렇기에 공식 홈페이지에서 이를 해석하기 위해 JSX 타입을 사용한다.
// JSX 타입의 경우 함수 형식(JSX.Element)과 클래스 형식(JSX.ElementClass)으로 나뉜다. 
type FCReactNode = JSX.Element;

function App() : FCReactNode {
    return (
        <React.StrictMode>  
        </React.StrictMode>
    )
}

const root = createRoot(document.createElement('root'));
root.render(<App />);

root.render()
```

**Comment by DGChoi3904** [comment]
번들 에러 - TS2345
커밋번호 : 5dd18b6b8564b993bcc4dcf8534c4b2638b6e2b3
에러코드
```
PS D:\dgchoi\KDT-2-Project-A-4> npx webpack
asset main.js 1.38 MiB [emitted] (name: main)
runtime modules 1.04 KiB 5 modules
modules by path ./node_modules/ 1.31 MiB
  modules by path ./node_modules/react-dom/ 1000 KiB 3 modules
  modules by path ./node_modules/react/ 85.7 KiB
    ./node_modules/react/index.js 190 bytes [built] [code generated]
    ./node_modules/react/cjs/react.development.js 85.5 KiB [built] [code generated]
  modules by path ./node_modules/scheduler/ 17.3 KiB
    ./node_modules/scheduler/index.js 198 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.development.js 17.1 KiB [built] [code generated]
  ./node_modules/react-router-dom/dist/index.js 36.1 KiB [built] [code generated]
  ./node_modules/@remix-run/router/dist/router.js 145 KiB [built] [code generated]
  ./node_modules/react-router/dist/index.js 49.4 KiB [built] [code generated]
modules by path ./develop/*.tsx 3.74 KiB
  ./develop/testReact.tsx 2.23 KiB [built] [code generated] [1 error]
  ./develop/Test.tsx 1.51 KiB [built] [code generated]

ERROR in D:\dgchoi\KDT-2-Project-A-4\develop\testReact.tsx
./develop/testReact.tsx 15:22-53
[tsl] ERROR in D:\dgchoi\KDT-2-Project-A-4\develop\testReact.tsx(15,23)
      TS2345: Argument of type 'HTMLElement | null' is not assignable to parameter of type 'Element | DocumentFragment'.
  Type 'null' is not assignable to type 'Element | DocumentFragment'.
ts-loader-default_e3b0c44298fc1c14

webpack 5.85.1 compiled with 1 error in 2882 ms
```
babelrc에 프리셋 env, react, typescript을 적용하고 번들 설정을 아래와 같이 적용.
```
const clientConfig = {
    entry: path.resolve(__dirname, "develop", "testReact.tsx"),
    mode: "development",
    module: {
        rules: [
            //TS로더
            {
                test: /\.tsx?$/,
                exclude: /node_modules/,
                use: "ts-loader",
            },
            //바벨로더
            {
                test: /\.(tsx?|js)$/,
                exclude: /node_modules/,
                use: "babel-loader"
            }

        ],
    },
    resolve: {
        extensions: [".tsx", ".ts", ".js"],
    },
    output: {
        filename: "main.js",
        path: path.resolve(__dirname, "dist")
    },
};
```
바벨로더를 설정하기 전에는 문제없이 번들되었으나, 적용후에 TS2345에러 발생. 타입 null을 허용할수 없다는 문제임을 확인함.

검색시 createRoot에 들어가는 document.getElementById("root")에 null이 지정될 수 있어 에러를 출력하는 것이라 확인. "!" 및 as HTMLElement를 써서 해결해보려고 했으나 실패.

GPT에 문의후 다음과 같이 작성하면 해결되는 것을 확인. 

에러 해결 커밋번호 : 8647102e7220afa21f1f6b10871b253dd3f865e0
코드 내용
```
const rootElement = document.getElementById("root") as HTMLElement;
if (rootElement) {
  const root = createRoot(rootElement);
  root.render(<App />);
} else {
  console.error("Root element not found");
}
```
null이 들어갈 수 있어 에러가 나는 문제이기에, null이 들어가면 에러가 발생하고 아닐시 실행되게 설정하는것으로 번들 문제 해결. 정말로 생각보다 간단한 방법으로 해결할 수 있었다.

**Comment by EXPNUNI-HUB** [comment]
에러는 생각보다 간단한 이유로 발생할 경우가 많지만, 우리가 어려워 보인다는 이유로 대부분 피하려고 함. 발생한 오류는 무조건 잡고 간다는 생각으로 하길 바람. 단, 이것은 시스템 원리로 인해 불가능 하거나 비효율적이라는 판단이 선 경우에만 다른 길로 가길 바람. 위처럼 정리하다 보면 오류메세지가 꽤 친절하다는 것을 알 수가 있음.

**Comment by DGChoi3904** [comment]
> 에러는 생각보다 간단한 이유로 발생할 경우가 많지만, 우리가 어려워 보인다는 이유로 대부분 피하려고 함. 발생한 오류는 무조건 잡고 간다는 생각으로 하길 바람. 단, 이것은 시스템 원리로 인해 불가능 하거나 비효율적이라는 판단이 선 경우에만 다른 길로 가길 바람. 위처럼 정리하다 보면 오류메세지가 꽤 친절하다는 것을 알 수가 있음.

피드백 주셔서 감사합니다. 참고하겠습니다.

**Comment by DGChoi3904** [comment]
팀원들의 프론트 작업 진행을 위해 main에 머지 한 다음 mariadb 설치작업을 진행하기로 함. 작업 완료

**Comment by EXPNUNI-HUB** [comment]
main에 대한 머지의 중요성을 모르면 git을 쓰나마나임.
main은 항상 최신화 시켜야 하며, 그 자체로 온전해야함.
또한 main 유지 시, 각 모듈 별 인터페이스에 대해서 확실히 정리해두길 바람.
각자 개발할 때는 잘 돌아갈 것처럼 느껴져도 실제 인터페이스 시에 오류가 막 터짐.
따라서 각 모듈에 대한 인터페이스는 main에서 잘 유지하기 바람.(그렇다고 마무리 안된 코드를 main에 올려둬서 git을 내려받은 모든 컴퓨터에서 오류가 터지게 하면 안됨.)

main 관리를 소홀히 할 경우, 후에 어떤 재앙이 닥칠지 모름.
그때는 기존 것을 다 날려버리고 처음부터 다시 하는 게 빠를 수 있음.
